title: "CHAPI is the Credential Handler API"
shorthand: "chapi.io"
description: "an open-source solution for communicating Verifiable Credentials on the Web"
url: "https://chapi.io" 

# Build settings
theme: jekyll-theme-cayman

exclude:
  - README.md

plugins:
  - jekyll-tabs
